kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/kim3928/do400-greeting-console'
      ref: main
  output:
    to:
      kind: DockerImage
      name: "quay.io/kim3928/greeting-console"
    pushSecret:
      name: quay-credentials
